export type Country = typeof COUNTRY_CODES[number];
export const COUNTRY_CODES = [
  {
    country: "Afghanistan",
    id: 939714,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AF",
    iso3: "AFG",
    level: 0,
    name: "Afghanistan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Aland",
    id: 939777,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AX",
    iso3: "ALD",
    level: 0,
    name: "Aland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Albania",
    id: 939780,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AL",
    iso3: "ALB",
    level: 0,
    name: "Albania",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Algeria",
    id: 939818,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "DZ",
    iso3: "DZA",
    level: 0,
    name: "Algeria",
    parentId: -1,
    sort: 0,
  },
  {
    country: "American Samoa",
    id: 939908,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AS",
    iso3: "ASM",
    level: 0,
    name: "American Samoa",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Andorra",
    id: 939910,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AD",
    iso3: "AND",
    level: 0,
    name: "Andorra",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Angola",
    id: 939912,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AO",
    iso3: "AGO",
    level: 0,
    name: "Angola",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Antarctica",
    id: 939980,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AQ",
    iso3: "ATA",
    level: 0,
    name: "Antarctica",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Antigua and Barbuda",
    id: 940021,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AG",
    iso3: "ATG",
    level: 0,
    name: "Antigua and Barbuda",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Argentina",
    id: 940023,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AR",
    iso3: "ARG",
    level: 0,
    name: "Argentina",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Armenia",
    id: 940205,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AM",
    iso3: "ARM",
    level: 0,
    name: "Armenia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Aruba",
    id: 940222,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AW",
    iso3: "ABW",
    level: 0,
    name: "Aruba",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Australia",
    id: 940224,
    initials: "A",
    isAudit: 0,
    ishot: 1,
    iso2: "AU",
    iso3: "AUS",
    level: 0,
    name: "Australia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Austria",
    id: 940457,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AT",
    iso3: "AUT",
    level: 0,
    name: "Austria",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Azerbaijan",
    id: 940477,
    initials: "A",
    isAudit: 0,
    ishot: 0,
    iso2: "AZ",
    iso3: "AZE",
    level: 0,
    name: "Azerbaijan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Bahrain",
    id: 940511,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BH",
    iso3: "BHR",
    level: 0,
    name: "Bahrain",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Bangladesh",
    id: 940513,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BD",
    iso3: "BGD",
    level: 0,
    name: "Bangladesh",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Barbados",
    id: 940536,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BB",
    iso3: "BRB",
    level: 0,
    name: "Barbados",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Belarus",
    id: 940539,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BY",
    iso3: "BLR",
    level: 0,
    name: "Belarus",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Belgium",
    id: 940561,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BE",
    iso3: "BEL",
    level: 0,
    name: "Belgium",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Belize",
    id: 940582,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BZ",
    iso3: "BLZ",
    level: 0,
    name: "Belize",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Benin",
    id: 940596,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BJ",
    iso3: "BEN",
    level: 0,
    name: "Benin",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Bermuda",
    id: 940614,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BM",
    iso3: "BMU",
    level: 0,
    name: "Bermuda",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Bhutan",
    id: 940616,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BT",
    iso3: "BTN",
    level: 0,
    name: "Bhutan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Bolivia",
    id: 940624,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BO",
    iso3: "BOL",
    level: 0,
    name: "Bolivia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Bosnia and Herzegovina",
    id: 940702,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BA",
    iso3: "BIH",
    level: 0,
    name: "Bosnia and Herzegovina",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Botswana",
    id: 940714,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BW",
    iso3: "BWA",
    level: 0,
    name: "Botswana",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Brazil",
    id: 940743,
    initials: "B",
    isAudit: 0,
    ishot: 1,
    iso2: "BR",
    iso3: "BRA",
    level: 0,
    name: "Brazil",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Brunei",
    id: 941163,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BN",
    iso3: "BRN",
    level: 0,
    name: "Brunei",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Bulgaria",
    id: 941166,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BG",
    iso3: "BGR",
    level: 0,
    name: "Bulgaria",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Burkina Faso",
    id: 941203,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BF",
    iso3: "BFA",
    level: 0,
    name: "Burkina Faso",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Burundi",
    id: 941268,
    initials: "B",
    isAudit: 0,
    ishot: 0,
    iso2: "BI",
    iso3: "BDI",
    level: 0,
    name: "Burundi",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Cambodia",
    id: 941296,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "KH",
    iso3: "KHM",
    level: 0,
    name: "Cambodia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Cameroon",
    id: 941335,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CM",
    iso3: "CMR",
    level: 0,
    name: "Cameroon",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Canada",
    id: 941377,
    initials: "C",
    isAudit: 0,
    ishot: 1,
    iso2: "CA",
    iso3: "CAN",
    level: 0,
    name: "Canada",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Cape Verde",
    id: 941646,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CV",
    iso3: "CPV",
    level: 0,
    name: "Cape Verde",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Saint Lucia",
    id: 949867,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "LC",
    iso3: "LCA",
    lat: "14.010304",
    level: 0,
    lng: "-60.988973",
    name: "Castries",
    parentId: 947034,
    sort: 0,
  },
  {
    country: "Cayman Islands",
    id: 941649,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "KY",
    iso3: "CYM",
    level: 0,
    name: "Cayman Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Central African Republic",
    id: 941651,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CF",
    iso3: "CAF",
    level: 0,
    name: "Central African Republic",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Chad",
    id: 941689,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "TD",
    iso3: "TCD",
    level: 0,
    name: "Chad",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Chile",
    id: 941722,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CL",
    iso3: "CHL",
    level: 0,
    name: "Chile",
    parentId: -1,
    sort: 0,
  },
  {
    country: "China Mainland",
    id: 941822,
    initials: "C",
    isAudit: 0,
    ishot: 1,
    iso2: "CN",
    iso3: "CHN",
    level: 0,
    name: "China Mainland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Colombia",
    id: 942253,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CO",
    iso3: "COL",
    level: 0,
    name: "Colombia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Comoros",
    id: 942355,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "KM",
    iso3: "COM",
    level: 0,
    name: "Comoros",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Congo (Brazzaville)",
    id: 942357,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CG",
    iso3: "COG",
    level: 0,
    name: "Congo (Brazzaville)",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Congo (Kinshasa)",
    id: 942385,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CD",
    iso3: "COD",
    level: 0,
    name: "Congo (Kinshasa)",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Cook Islands",
    id: 942485,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CK",
    iso3: "COK",
    level: 0,
    name: "Cook Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Costa Rica",
    id: 942487,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CR",
    iso3: "CRI",
    level: 0,
    name: "Costa Rica",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Croatia",
    id: 942508,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "HR",
    iso3: "HRV",
    level: 0,
    name: "Croatia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Cuba",
    id: 942529,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CU",
    iso3: "CUB",
    level: 0,
    name: "Cuba",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Curacao",
    id: 942571,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CW",
    iso3: "CUW",
    level: 0,
    name: "Curacao",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Cyprus",
    id: 942573,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CY",
    iso3: "CYP",
    level: 0,
    name: "Cyprus",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Czech Republic",
    id: 942581,
    initials: "C",
    isAudit: 0,
    ishot: 0,
    iso2: "CZ",
    iso3: "CZE",
    level: 0,
    name: "Czech Republic",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Denmark",
    id: 942601,
    initials: "D",
    isAudit: 0,
    ishot: 0,
    iso2: "DK",
    iso3: "DNK",
    level: 0,
    name: "Denmark",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Djibouti",
    id: 942619,
    initials: "D",
    isAudit: 0,
    ishot: 0,
    iso2: "DJ",
    iso3: "DJI",
    level: 0,
    name: "Djibouti",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Dominica",
    id: 942630,
    initials: "D",
    isAudit: 0,
    ishot: 0,
    iso2: "DM",
    iso3: "DMA",
    level: 0,
    name: "Dominica",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Dominican Republic",
    id: 942633,
    initials: "D",
    isAudit: 0,
    ishot: 0,
    iso2: "DO",
    iso3: "DOM",
    level: 0,
    name: "Dominican Republic",
    parentId: -1,
    sort: 0,
  },
  {
    country: "East Timor",
    id: 942694,
    initials: "E",
    isAudit: 0,
    ishot: 0,
    iso2: "TL",
    iso3: "TLS",
    level: 0,
    name: "East Timor",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Ecuador",
    id: 942697,
    initials: "E",
    isAudit: 0,
    ishot: 0,
    iso2: "EC",
    iso3: "ECU",
    level: 0,
    name: "Ecuador",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Egypt",
    id: 942755,
    initials: "E",
    isAudit: 0,
    ishot: 0,
    iso2: "EG",
    iso3: "EGY",
    level: 0,
    name: "Egypt",
    parentId: -1,
    sort: 0,
  },
  {
    country: "El Salvador",
    id: 942824,
    initials: "E",
    isAudit: 0,
    ishot: 0,
    iso2: "SV",
    iso3: "SLV",
    level: 0,
    name: "El Salvador",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Equatorial Guinea",
    id: 942852,
    initials: "E",
    isAudit: 0,
    ishot: 0,
    iso2: "GQ",
    iso3: "GNQ",
    level: 0,
    name: "Equatorial Guinea",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Eritrea",
    id: 942864,
    initials: "E",
    isAudit: 0,
    ishot: 0,
    iso2: "ER",
    iso3: "ERI",
    level: 0,
    name: "Eritrea",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Estonia",
    id: 942878,
    initials: "E",
    isAudit: 0,
    ishot: 0,
    iso2: "EE",
    iso3: "EST",
    level: 0,
    name: "Estonia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Ethiopia",
    id: 942892,
    initials: "E",
    isAudit: 0,
    ishot: 0,
    iso2: "ET",
    iso3: "ETH",
    level: 0,
    name: "Ethiopia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Falkland Islands",
    id: 942935,
    initials: "F",
    isAudit: 0,
    ishot: 0,
    iso2: "FK",
    iso3: "FLK",
    level: 0,
    name: "Falkland Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Faroe Islands",
    id: 942938,
    initials: "F",
    isAudit: 0,
    ishot: 0,
    iso2: "FO",
    iso3: "FRO",
    level: 0,
    name: "Faroe Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Federated States of Micronesia",
    id: 942942,
    initials: "F",
    isAudit: 0,
    ishot: 0,
    iso2: "FM",
    iso3: "FSM",
    level: 0,
    name: "Federated States of Micronesia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Fiji",
    id: 942944,
    initials: "F",
    isAudit: 0,
    ishot: 0,
    iso2: "FJ",
    iso3: "FJI",
    level: 0,
    name: "Fiji",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Finland",
    id: 942950,
    initials: "F",
    isAudit: 0,
    ishot: 0,
    iso2: "FI",
    iso3: "FIN",
    level: 0,
    name: "Finland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "France",
    id: 942987,
    initials: "F",
    isAudit: 0,
    ishot: 0,
    iso2: "FR",
    iso3: "FRA",
    level: 0,
    name: "France",
    parentId: -1,
    sort: 0,
  },
  {
    country: "French Polynesia",
    id: 943085,
    initials: "F",
    isAudit: 0,
    ishot: 0,
    iso2: "PF",
    iso3: "PYF",
    level: 0,
    name: "French Polynesia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Gabon",
    id: 943087,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GA",
    iso3: "GAB",
    level: 0,
    name: "Gabon",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Georgia",
    id: 943117,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GE",
    iso3: "GEO",
    level: 0,
    name: "Georgia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Germany",
    id: 943132,
    initials: "G",
    isAudit: 0,
    ishot: 1,
    iso2: "DE",
    iso3: "DEU",
    level: 0,
    name: "Germany",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Ghana",
    id: 943206,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GH",
    iso3: "GHA",
    level: 0,
    name: "Ghana",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Gibraltar",
    id: 943232,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GI",
    iso3: "GIB",
    level: 0,
    name: "Gibraltar",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Greece",
    id: 943235,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GR",
    iso3: "GRC",
    level: 0,
    name: "Greece",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Greenland",
    id: 943278,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GL",
    iso3: "GRL",
    level: 0,
    name: "Greenland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Grenada",
    id: 943306,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GD",
    iso3: "GRD",
    level: 0,
    name: "Grenada",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Guam",
    id: 943308,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GU",
    iso3: "GUM",
    level: 0,
    name: "Guam",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Guatemala",
    id: 943310,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GT",
    iso3: "GTM",
    level: 0,
    name: "Guatemala",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Guinea",
    id: 943359,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GN",
    iso3: "GIN",
    level: 0,
    name: "Guinea",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Guinea Bissau",
    id: 943397,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GW",
    iso3: "GNB",
    level: 0,
    name: "Guinea Bissau",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Guyana",
    id: 943414,
    initials: "G",
    isAudit: 0,
    ishot: 0,
    iso2: "GY",
    iso3: "GUY",
    level: 0,
    name: "Guyana",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Haiti",
    id: 943433,
    initials: "H",
    isAudit: 0,
    ishot: 0,
    iso2: "HT",
    iso3: "HTI",
    level: 0,
    name: "Haiti",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Honduras",
    id: 943447,
    initials: "H",
    isAudit: 0,
    ishot: 0,
    iso2: "HN",
    iso3: "HND",
    level: 0,
    name: "Honduras",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Hong Kong S.A.R.",
    id: 943484,
    initials: "H",
    isAudit: 0,
    ishot: 0,
    iso2: "HK",
    iso3: "HKG",
    level: 0,
    name: "Hong Kong S.A.R.",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Hungary",
    id: 943486,
    initials: "H",
    isAudit: 0,
    ishot: 0,
    iso2: "HU",
    iso3: "HUN",
    level: 0,
    name: "Hungary",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Iceland",
    id: 943527,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "IS",
    iso3: "ISL",
    level: 0,
    name: "Iceland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "India",
    id: 943545,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "IN",
    iso3: "IND",
    level: 0,
    name: "India",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Indonesia",
    id: 943791,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "ID",
    iso3: "IDN",
    level: 0,
    name: "Indonesia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Iran",
    id: 943930,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "IR",
    iso3: "IRN",
    level: 0,
    name: "Iran",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Iraq",
    id: 944024,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "IQ",
    iso3: "IRQ",
    level: 0,
    name: "Iraq",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Ireland",
    id: 944070,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "IE",
    iso3: "IRL",
    level: 0,
    name: "Ireland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Isle of Man",
    id: 944098,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "IM",
    iso3: "IMN",
    level: 0,
    name: "Isle of Man",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Israel",
    id: 944100,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "IL",
    iso3: "ISR",
    level: 0,
    name: "Israel",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Italy",
    id: 944113,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "IT",
    iso3: "ITA",
    level: 0,
    name: "Italy",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Ivory Coast",
    id: 944190,
    initials: "I",
    isAudit: 0,
    ishot: 0,
    iso2: "CI",
    iso3: "CIV",
    level: 0,
    name: "Ivory Coast",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Jamaica",
    id: 944235,
    initials: "J",
    isAudit: 0,
    ishot: 0,
    iso2: "JM",
    iso3: "JAM",
    level: 0,
    name: "Jamaica",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Japan",
    id: 944264,
    initials: "J",
    isAudit: 0,
    ishot: 0,
    iso2: "JP",
    iso3: "JPN",
    level: 0,
    name: "Japan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Jordan",
    id: 944378,
    initials: "J",
    isAudit: 0,
    ishot: 0,
    iso2: "JO",
    iso3: "JOR",
    level: 0,
    name: "Jordan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Kazakhstan",
    id: 944397,
    initials: "K",
    isAudit: 0,
    ishot: 0,
    iso2: "KZ",
    iso3: "KAZ",
    level: 0,
    name: "Kazakhstan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Kenya",
    id: 944508,
    initials: "K",
    isAudit: 0,
    ishot: 0,
    iso2: "KE",
    iso3: "KEN",
    level: 0,
    name: "Kenya",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Kiribati",
    id: 944550,
    initials: "K",
    isAudit: 0,
    ishot: 0,
    iso2: "KI",
    iso3: "KIR",
    level: 0,
    name: "Kiribati",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Kosovo",
    id: 944552,
    initials: "K",
    isAudit: 0,
    ishot: 0,
    iso3: "KOS",
    level: 0,
    name: "Kosovo",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Kuwait",
    id: 944559,
    initials: "K",
    isAudit: 0,
    ishot: 0,
    iso2: "KW",
    iso3: "KWT",
    level: 0,
    name: "Kuwait",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Kyrgyzstan",
    id: 944568,
    initials: "K",
    isAudit: 0,
    ishot: 0,
    iso2: "KG",
    iso3: "KGZ",
    level: 0,
    name: "Kyrgyzstan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Laos",
    id: 944589,
    initials: "L",
    isAudit: 0,
    ishot: 0,
    iso2: "LA",
    iso3: "LAO",
    level: 0,
    name: "Laos",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Latvia",
    id: 944617,
    initials: "L",
    isAudit: 0,
    ishot: 0,
    iso2: "LV",
    iso3: "LVA",
    level: 0,
    name: "Latvia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Lebanon",
    id: 944630,
    initials: "L",
    isAudit: 0,
    ishot: 0,
    iso2: "LB",
    iso3: "LBN",
    level: 0,
    name: "Lebanon",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Lesotho",
    id: 944642,
    initials: "L",
    isAudit: 0,
    ishot: 0,
    iso2: "LS",
    iso3: "LSO",
    level: 0,
    name: "Lesotho",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Liberia",
    id: 944658,
    initials: "L",
    isAudit: 0,
    ishot: 0,
    iso2: "LR",
    iso3: "LBR",
    level: 0,
    name: "Liberia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Libya",
    id: 944684,
    initials: "L",
    isAudit: 0,
    ishot: 0,
    iso2: "LY",
    iso3: "LBY",
    level: 0,
    name: "Libya",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Liechtenstein",
    id: 944741,
    initials: "L",
    isAudit: 0,
    ishot: 0,
    iso2: "LI",
    iso3: "LIE",
    level: 0,
    name: "Liechtenstein",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Lithuania",
    id: 944743,
    initials: "L",
    isAudit: 0,
    ishot: 0,
    iso2: "LT",
    iso3: "LTU",
    level: 0,
    name: "Lithuania",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Luxembourg",
    id: 944754,
    initials: "L",
    isAudit: 0,
    ishot: 0,
    iso2: "LU",
    iso3: "LUX",
    level: 0,
    name: "Luxembourg",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Macau S.A.R",
    id: 944761,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MO",
    iso3: "MAC",
    level: 0,
    name: "Macau S.A.R",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Macedonia",
    id: 944763,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MK",
    iso3: "MKD",
    level: 0,
    name: "Macedonia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Madagascar",
    id: 944770,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MG",
    iso3: "MDG",
    level: 0,
    name: "Madagascar",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Malawi",
    id: 944805,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MW",
    iso3: "MWI",
    level: 0,
    name: "Malawi",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Malaysia",
    id: 944843,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MY",
    iso3: "MYS",
    level: 0,
    name: "Malaysia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Maldives",
    id: 944889,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MV",
    iso3: "MDV",
    level: 0,
    name: "Maldives",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Mali",
    id: 944891,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "ML",
    iso3: "MLI",
    level: 0,
    name: "Mali",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Malta",
    id: 944930,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MT",
    iso3: "MLT",
    level: 0,
    name: "Malta",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Marshall Islands",
    id: 944932,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MH",
    iso3: "MHL",
    level: 0,
    name: "Marshall Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Mauritania",
    id: 944934,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MR",
    iso3: "MRT",
    level: 0,
    name: "Mauritania",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Mauritius",
    id: 944966,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MU",
    iso3: "MUS",
    level: 0,
    name: "Mauritius",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Mexico",
    id: 944969,
    initials: "M",
    isAudit: 0,
    ishot: 1,
    iso2: "MX",
    iso3: "MEX",
    level: 0,
    name: "Mexico",
    parentId: -1,
    sort: 300,
  },
  {
    country: "Moldova",
    id: 945190,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MD",
    iso3: "MDA",
    level: 0,
    name: "Moldova",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Monaco",
    id: 945201,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MC",
    iso3: "MCO",
    level: 0,
    name: "Monaco",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Mongolia",
    id: 945203,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MN",
    iso3: "MNG",
    level: 0,
    name: "Mongolia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Montenegro",
    id: 945248,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "ME",
    iso3: "MNE",
    level: 0,
    name: "Montenegro",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Morocco",
    id: 945251,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MA",
    iso3: "MAR",
    level: 0,
    name: "Morocco",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Mozambique",
    id: 945293,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MZ",
    iso3: "MOZ",
    level: 0,
    name: "Mozambique",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Myanmar",
    id: 945338,
    initials: "M",
    isAudit: 0,
    ishot: 0,
    iso2: "MM",
    iso3: "MMR",
    level: 0,
    name: "Myanmar",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Namibia",
    id: 945390,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "NA",
    iso3: "NAM",
    level: 0,
    name: "Namibia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Nepal",
    id: 945430,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "NP",
    iso3: "NPL",
    level: 0,
    name: "Nepal",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Netherlands",
    id: 945462,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "NL",
    iso3: "NLD",
    level: 0,
    name: "Netherlands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "New Caledonia",
    id: 945487,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "NC",
    iso3: "NCL",
    level: 0,
    name: "New Caledonia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "New Zealand",
    id: 945489,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "NZ",
    iso3: "NZL",
    level: 0,
    name: "New Zealand",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Nicaragua",
    id: 945535,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "NI",
    iso3: "NIC",
    level: 0,
    name: "Nicaragua",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Niger",
    id: 945571,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "NE",
    iso3: "NER",
    level: 0,
    name: "Niger",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Nigeria",
    id: 945595,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "NG",
    iso3: "NGA",
    level: 0,
    name: "Nigeria",
    parentId: -1,
    sort: 0,
  },
  {
    country: "North Korea",
    id: 945699,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "KP",
    iso3: "PRK",
    level: 0,
    name: "North Korea",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Northern Cyprus",
    id: 945740,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso3: "CYN",
    level: 0,
    name: "Northern Cyprus",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Northern Mariana Islands",
    id: 945743,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "MP",
    iso3: "MNP",
    level: 0,
    name: "Northern Mariana Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Norway",
    id: 945745,
    initials: "N",
    isAudit: 0,
    ishot: 0,
    iso2: "NO",
    iso3: "NOR",
    level: 0,
    name: "Norway",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Oman",
    id: 945799,
    initials: "O",
    isAudit: 0,
    ishot: 0,
    iso2: "OM",
    iso3: "OMN",
    level: 0,
    name: "Oman",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Pakistan",
    id: 945815,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PK",
    iso3: "PAK",
    level: 0,
    name: "Pakistan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Palau",
    id: 945864,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PW",
    iso3: "PLW",
    level: 0,
    name: "Palau",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Palestine",
    id: 945867,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PS",
    iso3: "PSE",
    level: 0,
    name: "Palestine",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Panama",
    id: 945872,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PA",
    iso3: "PAN",
    level: 0,
    name: "Panama",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Papua New Guinea",
    id: 945896,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PG",
    iso3: "PNG",
    level: 0,
    name: "Papua New Guinea",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Paraguay",
    id: 945936,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PY",
    iso3: "PRY",
    level: 0,
    name: "Paraguay",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Peru",
    id: 945990,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PE",
    iso3: "PER",
    level: 0,
    name: "Peru",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Philippines",
    id: 946103,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PH",
    iso3: "PHL",
    level: 0,
    name: "Philippines",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Poland",
    id: 946174,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PL",
    iso3: "POL",
    level: 0,
    name: "Poland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Portugal",
    id: 946215,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PT",
    iso3: "PRT",
    level: 0,
    name: "Portugal",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Puerto Rico",
    id: 946259,
    initials: "P",
    isAudit: 0,
    ishot: 0,
    iso2: "PR",
    iso3: "PRI",
    level: 0,
    name: "Puerto Rico",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Qatar",
    id: 946264,
    initials: "Q",
    isAudit: 0,
    ishot: 0,
    iso2: "QA",
    iso3: "QAT",
    level: 0,
    name: "Qatar",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Romania",
    id: 946267,
    initials: "R",
    isAudit: 0,
    ishot: 0,
    iso2: "RO",
    iso3: "ROU",
    level: 0,
    name: "Romania",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Russia",
    id: 946349,
    initials: "R",
    isAudit: 0,
    ishot: 1,
    iso2: "RU",
    iso3: "RUS",
    level: 0,
    name: "Russia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Rwanda",
    id: 947018,
    initials: "R",
    isAudit: 0,
    ishot: 0,
    iso2: "RW",
    iso3: "RWA",
    level: 0,
    name: "Rwanda",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Saint Kitts and Nevis",
    id: 947031,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "KN",
    iso3: "KNA",
    level: 0,
    name: "Saint Kitts and Nevis",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Saint Lucia",
    id: 947033,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "LC",
    iso3: "LCA",
    level: 0,
    name: "Saint Lucia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Saint Vincent and the Grenadines",
    id: 947035,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "VC",
    iso3: "VCT",
    level: 0,
    name: "Saint Vincent and the Grenadines",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Samoa",
    id: 947037,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "WS",
    iso3: "WSM",
    level: 0,
    name: "Samoa",
    parentId: -1,
    sort: 0,
  },
  {
    country: "San Marino",
    id: 947039,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SM",
    iso3: "SMR",
    level: 0,
    name: "San Marino",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Sao Tome and Principe",
    id: 947041,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "ST",
    iso3: "STP",
    level: 0,
    name: "Sao Tome and Principe",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Saudi Arabia",
    id: 947044,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SA",
    iso3: "SAU",
    level: 0,
    name: "Saudi Arabia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Senegal",
    id: 947087,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SN",
    iso3: "SEN",
    level: 0,
    name: "Senegal",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Serbia",
    id: 947109,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "RS",
    iso3: "SRB",
    level: 0,
    name: "Serbia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Seychelles",
    id: 947124,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SC",
    iso3: "SYC",
    level: 0,
    name: "Seychelles",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Sierra Leone",
    id: 947126,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SL",
    iso3: "SLE",
    level: 0,
    name: "Sierra Leone",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Singapore",
    id: 947132,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SG",
    iso3: "SGP",
    lat: "",
    level: 0,
    lng: "",
    name: "Singapore",
    parentId: -1,
    pop: "",
    sort: 0,
  },
  {
    country: "Sint Maarten",
    id: 949844,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SX",
    iso3: "SXM",
    lat: "18.074362",
    level: 0,
    lng: "-63.053718",
    name: "Sint Maarten",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Slovakia",
    id: 947134,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SK",
    iso3: "SVK",
    level: 0,
    name: "Slovakia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Slovenia",
    id: 947148,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SI",
    iso3: "SVN",
    level: 0,
    name: "Slovenia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Solomon Islands",
    id: 947153,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SB",
    iso3: "SLB",
    level: 0,
    name: "Solomon Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Somalia",
    id: 947160,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SO",
    iso3: "SOM",
    level: 0,
    name: "Somalia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Somaliland",
    id: 947199,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso3: "SOL",
    level: 0,
    name: "Somaliland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "South Africa",
    id: 947207,
    initials: "S",
    isAudit: 0,
    ishot: 1,
    iso2: "ZA",
    iso3: "ZAF",
    level: 0,
    name: "South Africa",
    parentId: -1,
    sort: 0,
  },
  {
    country: "South Georgia and the Islands",
    id: 947289,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "GS",
    iso3: "SGS",
    level: 0,
    name: "South Georgia and the Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "South Korea",
    id: 947291,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "KR",
    iso3: "KOR",
    level: 0,
    name: "South Korea",
    parentId: -1,
    sort: 0,
  },
  {
    country: "South Sudan",
    id: 947335,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SS",
    iso3: "SSD",
    level: 0,
    name: "South Sudan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Spain",
    id: 947361,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "ES",
    iso3: "ESP",
    level: 0,
    name: "Spain",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Sri Lanka",
    id: 947428,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "LK",
    iso3: "LKA",
    level: 0,
    name: "Sri Lanka",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Sudan",
    id: 947455,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SD",
    iso3: "SDN",
    level: 0,
    name: "Sudan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Suriname",
    id: 947501,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SR",
    iso3: "SUR",
    level: 0,
    name: "Suriname",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Svalbard and Jan Mayen Islands",
    id: 947521,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SJ",
    iso3: "SJM",
    level: 0,
    name: "Svalbard and Jan Mayen Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Swaziland",
    id: 947524,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SZ",
    iso3: "SWZ",
    level: 0,
    name: "Swaziland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Sweden",
    id: 947536,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SE",
    iso3: "SWE",
    level: 0,
    name: "Sweden",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Switzerland",
    id: 947592,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "CH",
    iso3: "CHE",
    level: 0,
    name: "Switzerland",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Syria",
    id: 947647,
    initials: "S",
    isAudit: 0,
    ishot: 0,
    iso2: "SY",
    iso3: "SYR",
    level: 0,
    name: "Syria",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Taiwan",
    id: 947682,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TW",
    iso3: "TWN",
    level: 0,
    name: "Taiwan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Tajikistan",
    id: 947728,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TJ",
    iso3: "TJK",
    level: 0,
    name: "Tajikistan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Tanzania",
    id: 947742,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TZ",
    iso3: "TZA",
    level: 0,
    name: "Tanzania",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Thailand",
    id: 947825,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TH",
    iso3: "THA",
    level: 0,
    name: "Thailand",
    parentId: -1,
    sort: 0,
  },
  {
    country: "The Bahamas",
    id: 947979,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "BS",
    iso3: "BHS",
    level: 0,
    name: "The Bahamas",
    parentId: -1,
    sort: 0,
  },
  {
    country: "The Gambia",
    id: 947982,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "GM",
    iso3: "GMB",
    level: 0,
    name: "The Gambia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Togo",
    id: 947994,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TG",
    iso3: "TGO",
    level: 0,
    name: "Togo",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Tonga",
    id: 948004,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TO",
    iso3: "TON",
    level: 0,
    name: "Tonga",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Trinidad and Tobago",
    id: 948007,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TT",
    iso3: "TTO",
    level: 0,
    name: "Trinidad and Tobago",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Tunisia",
    id: 948012,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TN",
    iso3: "TUN",
    level: 0,
    name: "Tunisia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Turkey",
    id: 948061,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TR",
    iso3: "TUR",
    level: 0,
    name: "Turkey",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Turkmenistan",
    id: 948216,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TM",
    iso3: "TKM",
    level: 0,
    name: "Turkmenistan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Turks and Caicos Islands",
    id: 948235,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TC",
    iso3: "TCA",
    level: 0,
    name: "Turks and Caicos Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Tuvalu",
    id: 948237,
    initials: "T",
    isAudit: 0,
    ishot: 0,
    iso2: "TV",
    iso3: "TUV",
    level: 0,
    name: "Tuvalu",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Uganda",
    id: 948239,
    initials: "U",
    isAudit: 0,
    ishot: 0,
    iso2: "UG",
    iso3: "UGA",
    level: 0,
    name: "Uganda",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Ukraine",
    id: 948323,
    initials: "U",
    isAudit: 0,
    ishot: 0,
    iso2: "UA",
    iso3: "UKR",
    level: 0,
    name: "Ukraine",
    parentId: -1,
    sort: 0,
  },
  {
    country: "United Arab Emirates",
    id: 948403,
    initials: "U",
    isAudit: 0,
    ishot: 1,
    iso2: "AE",
    iso3: "ARE",
    level: 0,
    name: "United Arab Emirates",
    parentId: -1,
    sort: 0,
  },
  {
    country: "United Kingdom",
    id: 948418,
    initials: "U",
    isAudit: 0,
    ishot: 1,
    iso2: "GB",
    iso3: "GBR",
    level: 0,
    name: "United Kingdom",
    parentId: -1,
    sort: 0,
  },
  {
    country: "United States of America",
    id: 939713,
    initials: "U",
    isAudit: 0,
    ishot: 1,
    iso2: "US",
    iso3: "USA",
    level: 0,
    name: "United States of America",
    parentId: -1,
    sort: 0,
  },
  {
    country: "United States Virgin Islands",
    id: 949344,
    initials: "U",
    isAudit: 0,
    ishot: 0,
    iso2: "VI",
    iso3: "VIR",
    level: 0,
    name: "United States Virgin Islands",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Uruguay",
    id: 949346,
    initials: "U",
    isAudit: 0,
    ishot: 0,
    iso2: "UY",
    iso3: "URY",
    level: 0,
    name: "Uruguay",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Uzbekistan",
    id: 949395,
    initials: "U",
    isAudit: 0,
    ishot: 0,
    iso2: "UZ",
    iso3: "UZB",
    level: 0,
    name: "Uzbekistan",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Vanuatu",
    id: 949438,
    initials: "V",
    isAudit: 0,
    ishot: 0,
    iso2: "VU",
    iso3: "VUT",
    level: 0,
    name: "Vanuatu",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Vatican (Holy Sea)",
    id: 949443,
    initials: "V",
    isAudit: 0,
    ishot: 0,
    iso2: "VA",
    iso3: "VAT",
    level: 0,
    name: "Vatican (Holy Sea)",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Venezuela",
    id: 949445,
    initials: "V",
    isAudit: 0,
    ishot: 0,
    iso2: "VE",
    iso3: "VEN",
    level: 0,
    name: "Venezuela",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Vietnam",
    id: 949516,
    initials: "V",
    isAudit: 0,
    ishot: 0,
    iso2: "VN",
    iso3: "VNM",
    level: 0,
    name: "Vietnam",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Western Sahara",
    id: 949632,
    initials: "W",
    isAudit: 0,
    ishot: 0,
    iso2: "EH",
    iso3: "SAH",
    level: 0,
    name: "Western Sahara",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Yemen",
    id: 949634,
    initials: "Y",
    isAudit: 0,
    ishot: 0,
    iso2: "YE",
    iso3: "YEM",
    level: 0,
    name: "Yemen",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Zambia",
    id: 949669,
    initials: "Z",
    isAudit: 0,
    ishot: 0,
    iso2: "ZM",
    iso3: "ZMB",
    level: 0,
    name: "Zambia",
    parentId: -1,
    sort: 0,
  },
  {
    country: "Zimbabwe",
    id: 949708,
    initials: "Z",
    isAudit: 0,
    ishot: 0,
    iso2: "ZW",
    iso3: "ZWE",
    level: 0,
    name: "Zimbabwe",
    parentId: -1,
    sort: 0,
  },
] as const;
