import type { CarData } from "@/types/car-data"

// Mock data for the API
export const carDataByCountry: Record<string, CarData[]> = {
  global: [
    {
      id: "1",
      make: "Tesla",
      model: "Model S Plaid",
      year: 2023,
      zeroToHundred: 2.1,
      hundredToTwoHundred: 4.3,
      quarterMile: 9.23,
      power: 1020,
      modifications: null,
    },
    {
      id: "2",
      make: "Porsche",
      model: "911 Turbo S",
      year: 2022,
      zeroToHundred: 2.7,
      hundredToTwoHundred: 5.9,
      quarterMile: 10.1,
      power: 640,
      modifications: null,
    },
    {
      id: "3",
      make: "BMW",
      model: "M5 Competition",
      year: 2021,
      zeroToHundred: 3.3,
      hundredToTwoHundred: 7.1,
      quarterMile: 11.1,
      power: 617,
      modifications: ["ECU Tune", "Exhaust"],
    },
    {
      id: "4",
      make: "Audi",
      model: "RS7",
      year: 2022,
      zeroToHundred: 3.6,
      hundredToTwoHundred: 8.2,
      quarterMile: 11.6,
      power: 591,
      modifications: null,
    },
    {
      id: "5",
      make: "Mercedes-Benz",
      model: "AMG GT 63 S",
      year: 2021,
      zeroToHundred: 3.2,
      hundredToTwoHundred: 7.5,
      quarterMile: 11.2,
      power: 630,
      modifications: null,
    },
    {
      id: "6",
      make: "Lamborghini",
      model: "Aventador SVJ",
      year: 2020,
      zeroToHundred: 2.8,
      hundredToTwoHundred: 5.8,
      quarterMile: 10.3,
      power: 759,
      modifications: null,
    },
    {
      id: "7",
      make: "Ferrari",
      model: "SF90 Stradale",
      year: 2022,
      zeroToHundred: 2.5,
      hundredToTwoHundred: 4.9,
      quarterMile: 9.7,
      power: 986,
      modifications: null,
    },
    {
      id: "8",
      make: "McLaren",
      model: "765LT",
      year: 2021,
      zeroToHundred: 2.7,
      hundredToTwoHundred: 5.5,
      quarterMile: 9.9,
      power: 755,
      modifications: null,
    },
    {
      id: "9",
      make: "Dodge",
      model: "Challenger SRT Demon",
      year: 2018,
      zeroToHundred: 2.3,
      hundredToTwoHundred: 6.1,
      quarterMile: 9.65,
      power: 840,
      modifications: ["Drag Radials", "Race Fuel Tune"],
    },
    {
      id: "10",
      make: "Chevrolet",
      model: "Corvette Z06",
      year: 2023,
      zeroToHundred: 2.6,
      hundredToTwoHundred: 6.3,
      quarterMile: 10.5,
      power: 670,
      modifications: null,
    },
    {
      id: "11",
      make: "Nissan",
      model: "GT-R Nismo",
      year: 2021,
      zeroToHundred: 2.5,
      hundredToTwoHundred: 6.7,
      quarterMile: 10.8,
      power: 600,
      modifications: ["Downpipes", "ECU Tune"],
    },
    {
      id: "12",
      make: "Toyota",
      model: "Supra GR",
      year: 2022,
      zeroToHundred: 3.9,
      hundredToTwoHundred: 9.5,
      quarterMile: 12.2,
      power: 382,
      modifications: ["ECU Tune"],
    },
  ],
  usa: [
    {
      id: "1",
      make: "Tesla",
      model: "Model S Plaid",
      year: 2023,
      zeroToHundred: 2.1,
      hundredToTwoHundred: 4.3,
      quarterMile: 9.23,
      power: 1020,
      modifications: null,
    },
    {
      id: "9",
      make: "Dodge",
      model: "Challenger SRT Demon",
      year: 2018,
      zeroToHundred: 2.3,
      hundredToTwoHundred: 6.1,
      quarterMile: 9.65,
      power: 840,
      modifications: ["Drag Radials", "Race Fuel Tune"],
    },
    {
      id: "10",
      make: "Chevrolet",
      model: "Corvette Z06",
      year: 2023,
      zeroToHundred: 2.6,
      hundredToTwoHundred: 6.3,
      quarterMile: 10.5,
      power: 670,
      modifications: null,
    },
    {
      id: "13",
      make: "Ford",
      model: "Mustang Shelby GT500",
      year: 2022,
      zeroToHundred: 3.4,
      hundredToTwoHundred: 7.8,
      quarterMile: 11.3,
      power: 760,
      modifications: null,
    },
    {
      id: "14",
      make: "Cadillac",
      model: "CT5-V Blackwing",
      year: 2022,
      zeroToHundred: 3.6,
      hundredToTwoHundred: 8.1,
      quarterMile: 11.7,
      power: 668,
      modifications: null,
    },
  ],
  germany: [
    {
      id: "2",
      make: "Porsche",
      model: "911 Turbo S",
      year: 2022,
      zeroToHundred: 2.7,
      hundredToTwoHundred: 5.9,
      quarterMile: 10.1,
      power: 640,
      modifications: null,
    },
    {
      id: "3",
      make: "BMW",
      model: "M5 Competition",
      year: 2021,
      zeroToHundred: 3.3,
      hundredToTwoHundred: 7.1,
      quarterMile: 11.1,
      power: 617,
      modifications: ["ECU Tune", "Exhaust"],
    },
    {
      id: "4",
      make: "Audi",
      model: "RS7",
      year: 2022,
      zeroToHundred: 3.6,
      hundredToTwoHundred: 8.2,
      quarterMile: 11.6,
      power: 591,
      modifications: null,
    },
    {
      id: "5",
      make: "Mercedes-Benz",
      model: "AMG GT 63 S",
      year: 2021,
      zeroToHundred: 3.2,
      hundredToTwoHundred: 7.5,
      quarterMile: 11.2,
      power: 630,
      modifications: null,
    },
    {
      id: "15",
      make: "Porsche",
      model: "Taycan Turbo S",
      year: 2023,
      zeroToHundred: 2.8,
      hundredToTwoHundred: 6.0,
      quarterMile: 10.7,
      power: 750,
      modifications: null,
    },
  ],
  japan: [
    {
      id: "11",
      make: "Nissan",
      model: "GT-R Nismo",
      year: 2021,
      zeroToHundred: 2.5,
      hundredToTwoHundred: 6.7,
      quarterMile: 10.8,
      power: 600,
      modifications: ["Downpipes", "ECU Tune"],
    },
    {
      id: "12",
      make: "Toyota",
      model: "Supra GR",
      year: 2022,
      zeroToHundred: 3.9,
      hundredToTwoHundred: 9.5,
      quarterMile: 12.2,
      power: 382,
      modifications: ["ECU Tune"],
    },
    {
      id: "16",
      make: "Lexus",
      model: "LC 500",
      year: 2022,
      zeroToHundred: 4.7,
      hundredToTwoHundred: 10.8,
      quarterMile: 13.2,
      power: 471,
      modifications: null,
    },
    {
      id: "17",
      make: "Honda",
      model: "NSX Type S",
      year: 2022,
      zeroToHundred: 3.0,
      hundredToTwoHundred: 7.2,
      quarterMile: 11.0,
      power: 600,
      modifications: null,
    },
    {
      id: "18",
      make: "Subaru",
      model: "WRX STI S209",
      year: 2020,
      zeroToHundred: 4.9,
      hundredToTwoHundred: 12.5,
      quarterMile: 13.3,
      power: 341,
      modifications: null,
    },
  ],
  italy: [
    {
      id: "6",
      make: "Lamborghini",
      model: "Aventador SVJ",
      year: 2020,
      zeroToHundred: 2.8,
      hundredToTwoHundred: 5.8,
      quarterMile: 10.3,
      power: 759,
      modifications: null,
    },
    {
      id: "7",
      make: "Ferrari",
      model: "SF90 Stradale",
      year: 2022,
      zeroToHundred: 2.5,
      hundredToTwoHundred: 4.9,
      quarterMile: 9.7,
      power: 986,
      modifications: null,
    },
    {
      id: "19",
      make: "Maserati",
      model: "MC20",
      year: 2022,
      zeroToHundred: 2.9,
      hundredToTwoHundred: 6.5,
      quarterMile: 10.9,
      power: 621,
      modifications: null,
    },
    {
      id: "20",
      make: "Alfa Romeo",
      model: "Giulia Quadrifoglio",
      year: 2022,
      zeroToHundred: 3.9,
      hundredToTwoHundred: 9.2,
      quarterMile: 12.1,
      power: 505,
      modifications: null,
    },
  ],
  uk: [
    {
      id: "8",
      make: "McLaren",
      model: "765LT",
      year: 2021,
      zeroToHundred: 2.7,
      hundredToTwoHundred: 5.5,
      quarterMile: 9.9,
      power: 755,
      modifications: null,
    },
    {
      id: "21",
      make: "Aston Martin",
      model: "DBS Superleggera",
      year: 2022,
      zeroToHundred: 3.4,
      hundredToTwoHundred: 7.0,
      quarterMile: 11.2,
      power: 715,
      modifications: null,
    },
    {
      id: "22",
      make: "Jaguar",
      model: "F-Type R",
      year: 2022,
      zeroToHundred: 3.7,
      hundredToTwoHundred: 8.5,
      quarterMile: 11.7,
      power: 575,
      modifications: null,
    },
    {
      id: "23",
      make: "Lotus",
      model: "Evija",
      year: 2023,
      zeroToHundred: 2.9,
      hundredToTwoHundred: 5.8,
      quarterMile: 9.8,
      power: 1972,
      modifications: null,
    },
  ],
}
